apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGkxMXV0dHk=
  CLOUDINARY_KEY: OTM0OTQyNjk3MTcxMjg1
  CLOUDINARY_SECRET: MmxES1RHT0pUcVkweTJJRG1YVXVXYVZXMVR3
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljMkZ1ZEdodmMyZ3lOekE0SWl3aVlTSTZJbU50YzNKemVuUnhhekF6TlRFeWQzSTFibkJvZUc1a2IyTWlmUS4xeGVjTVB3dWZFYmlpVmlQU1ZLMU1n
  DB_URL: bW9uZ29kYitzcnY6Ly9raWNrc2FudGhvc2g1NjY3X2RiX3VzZXI6QWRtaW5ANTY2N0BjbHVzdGVyMC5jbWo1anA3Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
